=== jowdaaaa/BSIT-Things/BSIT-2F(AY 2023-2024)/2ND SEMESTER/Integrative Programming ad Technologies 1/Activity 4/JudahPauloVinas_book_list.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="book_list">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="book" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="book">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="ebook" type="xs:string"/>
            <xs:element name="publisher" type="xs:string"/>
            <xs:element name="language" type="xs:string"/>
            <xs:element name="pages" type="xs:integer"/>
        </xs:sequence>
         <xs:attribute name="author" type="xs:string"/>
    </xs:complexType>
</xs:element>

</xs:schema>

=== jowdaaaa/BSIT-Things/BSIT-2F(AY 2023-2024)/2ND SEMESTER/Integrative Programming ad Technologies 1/Activity 5/JudahPauloVinas_5.xml
<?xml version="1.0"?>

<book_list xmlns="https://www.javajeff.ca/"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="JudahPauloVinas_book_list.xsd">
            
    <book author="Tim Winton">
        <title>Cloudstreet</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/343881.Cloudstreet]]></ebook>
        <publisher>McPhee Gribble</publisher>
        <language>English</language>
        <pages>426</pages>
    </book>
    <book author="Christos Tsiolkas">
        <title>The Slap</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/5396496-the-slap?from_search=true&from_srp=true&qid=NqBOrdbAxu&rank=1]]></ebook>
        <publisher>Allen &amp; Row</publisher>
        <language>English</language>
        <pages>484</pages>
    </book>
    <book author="Thomas Keneally">
        <title>Schindler's Ark</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/268302.Schindler_s_Ark?from_search=true&from_srp=true&qid=5aWSbXI3At&rank=1]]></ebook>
        <publisher>Hoddler &amp; Stoughton</publisher>
        <language>English</language>
        <pages>400</pages>
    </book>
    <book author="Liane Moriarty">
        <title>Big Little Lies</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/19486412-big-little-lies]]></ebook>
        <publisher>Penguin Group</publisher>
        <language>English</language>
        <pages>460</pages>
    </book>
    <book author="Peter Carey">
        <title>Oscar and Lucinda</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/187518.Oscar_and_Lucinda]]></ebook>
        <publisher>University of Queensland Press</publisher>
        <language>English</language>
        <pages>512</pages>
    </book>
    <book author="Marcus Zusak">
        <title>The Thorn Birds</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/830.The_Thorn_Birds]]></ebook>
        <publisher>Harper and Row</publisher>
        <language>English</language>
        <pages>692</pages>
    </book>
    <book author="Richard Flanagan">
        <title>The Book Thief</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/19063.The_Book_Thief]]></ebook>
        <publisher>Picador</publisher>
        <language>English</language>
        <pages>552</pages>
    </book>
    <book author="Hannah Kent">
        <title>The Narrow Road to the Deep North</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/17333223-the-narrow-road-to-the-deep-north]]></ebook>
        <publisher>Knopf</publisher>
        <language>English</language>
        <pages>464</pages>
    </book>
    <book author="Hannah Kent">
        <title>Burial Rites</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/18273332-burial-rites]]></ebook>
        <publisher>Little, Brown and Company</publisher>
        <language>English</language>
        <pages>336</pages>
    </book>
    <book author="David Malouf">
        <title>Remembering Babylon</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/46161.Remembering_Babylon]]></ebook>
        <publisher>Chatto and Windus</publisher>
        <language>English</language>
        <pages>213</pages>
    </book>
    <book author="Geraldine Brooks">
        <title>March</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/6365.March]]></ebook>
        <publisher>Viking</publisher>
        <language>English</language>
        <pages>280</pages>
    </book>
    <book author="David Marr">
        <title>Patrick White: A Life</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/19976.Patrick_White]]></ebook>
        <publisher>Random House</publisher>
        <language>English</language>
        <pages>736</pages>
    </book>
    <book author="Tara June Winch">
        <title>The Yield</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/40220035-the-yield]]></ebook>
        <publisher>Hamish Hamillton</publisher>
        <language>English</language>
        <pages>352</pages>
    </book>
    <book author="Kate Grenville">
        <title>The Secret River</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/13907.The_Secret_River]]></ebook>
        <publisher>Canongate Books</publisher>
        <language>English</language>
        <pages>334</pages>
    </book>
    <book author="Joan Lindsay">
        <title>Picnic at Hanging Rock</title>
        <ebook><![CDATA[https://www.goodreads.com/book/show/291507.Picnic_at_Hanging_Rock]]></ebook>
        <publisher>Cheshire Publishing</publisher>
        <language>English</language>
        <pages>212</pages>
    </book>
</book_list>
